2025-06-09 19:05:37.349520 - CRITICAL STARTUP ERROR: [WinError 193] %1 is not a valid Win32 application
Traceback (most recent call last):
  File "C:\Users\freax\OneDrive\Desktop\ig_reels_analytics\ig_reels_analytics.py", line 74, in <module>
    logged_in_instaloader_username = login_sequence(
        root_tk_window,
    ...<2 lines>...
        app._hide_blocking_overlay  # Pass the hide overlay method
    )
  File "C:\Users\freax\OneDrive\Desktop\ig_reels_analytics\ui.py", line 1080, in login_sequence
    challenge_driver = webdriver.Chrome(service=service, options=headed_options)
  File "C:\Users\freax\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 47, in __init__
    super().__init__(
    ~~~~~~~~~~~~~~~~^
        browser_name=DesiredCapabilities.CHROME["browserName"],
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
        keep_alive=keep_alive,
        ^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\freax\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 58, in __init__
    self.service.start()
    ~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\freax\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\common\service.py", line 102, in start
    self._start_process(self._path)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\freax\AppData\Local\Programs\Python\Python313\Lib\site-packages\selenium\webdriver\common\service.py", line 213, in _start_process
    self.process = subprocess.Popen(
                   ~~~~~~~~~~~~~~~~^
        cmd,
        ^^^^
    ...<7 lines>...
        **self.popen_kw,
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\freax\AppData\Local\Programs\Python\Python313\Lib\subprocess.py", line 1039, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
    ~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                        pass_fds, cwd, env,
                        ^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
                        gid, gids, uid, umask,
                        ^^^^^^^^^^^^^^^^^^^^^^
                        start_new_session, process_group)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\freax\AppData\Local\Programs\Python\Python313\Lib\subprocess.py", line 1551, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
                             # no special security
                             ^^^^^^^^^^^^^^^^^^^^^
    ...<4 lines>...
                             cwd,
                             ^^^^
                             startupinfo)
                             ^^^^^^^^^^^^
OSError: [WinError 193] %1 is not a valid Win32 application

